# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cgioAejCQEYKE4M4ndTn0O1YZ0wlKH4Y
"""

#!/usr/bin/env python

import rospy
from std_srvs.srv import Empty

def main():
    rospy.init_node('main_node')
    rospy.wait_for_service('/go_to_kitchen')
    go_to_kitchen_service = rospy.ServiceProxy('/go_to_kitchen', Empty)
    rospy.wait_for_service('/stop')
    stop_service = rospy.ServiceProxy('/stop', Empty)
    rospy.wait_for_service('/go_home')
    go_home_service = rospy.ServiceProxy('/go_home', Empty)

    # Go to kitchen
    rospy.loginfo("Going to kitchen.")
    go_to_kitchen_service()
    rospy.loginfo("Reached the kitchen.")

    # Stop
    stop_service()
    rospy.loginfo("Stopped.")

    # Go home
    rospy.loginfo("Going back home.")
    go_home_service()
    rospy.loginfo("Reached home.")

    # Stop again
    stop_service()
    rospy.loginfo("Stopped.")

if __name__ == '__main__':
    main()