# -*- coding: utf-8 -*-
"""navigation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cgioAejCQEYKE4M4ndTn0O1YZ0wlKH4Y
"""

#!/usr/bin/env python

import rospy
import time
from std_srvs.srv import Empty, EmptyResponse

def handle_go_home(request):
    rospy.loginfo("Going to home.")
    time.sleep(2)
    rospy.loginfo("Arrived.")
    return EmptyResponse()

def handle_go_to_kitchen(request):
    rospy.loginfo("Going to kitchen.")
    time.sleep(2)
    rospy.loginfo("Arrived.")
    return EmptyResponse()

def handle_stop(request):
    rospy.loginfo("Stop!")
    return EmptyResponse()

def navigation_server():
    rospy.init_node('navigation_server')
    rospy.Service('/go_home', Empty, handle_go_home)
    rospy.Service('/go_to_kitchen', Empty, handle_go_to_kitchen)
    rospy.Service('/stop', Empty, handle_stop)
    rospy.loginfo("Navigation server is running.")
    rospy.spin()

if __name__ == '__main__':
    navigation_server()